import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlin: String = "1.3.61"

    const val io_ktor: String = "1.3.1"

    const val com_android_tools_build_gradle: String = "3.5.3"

    const val androidx_test_runner: String = "1.2.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val kotlinx_serialization_runtime_common: String = "0.14.0"

    const val kotlinx_serialization_runtime_native: String = "0.13.0"

    const val kotlinx_coroutines_core_common: String = "1.3.3"

    const val kotlinx_coroutines_core_native: String = "1.3.1"

    const val kotlinx_serialization_runtime: String = "0.14.0"

    const val kotlinx_coroutines_android: String = "1.3.3"

    const val kotlinx_coroutines_test: String = "1.3.3"

    const val constraintlayout: String = "1.1.3"

    const val espresso_core: String = "3.2.0"

    const val lint_gradle: String = "26.5.3"

    const val appcompat: String = "1.1.0"

    const val core_ktx: String = "1.2.0"

    const val aapt2: String = "3.5.3-5435860"

    const val junit: String = "4.13"

    /**
     * Current version: "5.4.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.1.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
